### ISSUE TITLE
On the xbox-wireless-controller the D-PAD UP and DOWN in opposite directions.

### ISSUE THREAD

**Issue by luhcow** [o0Zz/sys-con#1]
If I push the stick up, the character moves down. If I push the stick down, the character moves up. This happens on both sticks. It is consistent across games and UI. The rest of the functions behave correctly.

**Environment**

- Firmware 18.0.1
- Atmosphere 1.7.0
- Sys-Con v1.0.2

Pushing the stick up in hbmenu displays -3xxxx. The log shows that the controller is recognized as xboxone, this should be correct.

**Comment by o0Zz** [comment]
Could you try this driver and let me know if it properly fix this issue.

Thanks
[sys-con-1.0.2+2.zip](https://github.com/user-attachments/files/15569725/sys-con-1.0.2%2B2.zip)

**Comment by o0Zz** [comment]
Try to latest release -> https://github.com/o0Zz/sys-con/releases/tag/1.1.0

If it doesn't works, please provide the logs in trace mode. I'm not sure to understand what's wrong here

**Comment by o0Zz** [comment]
I close this issue since there is not update. Try the latest version that add supports forcontrollers and fix some issues -> https://github.com/o0Zz/sys-con/releases
If it don't help, re-open a ticket with the logs in trace https://github.com/o0Zz/sys-con/?tab=readme-ov-file#logs
