### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Zhuwenxue2002** [o0Zz/sys-con#10]
I'm very glad you took over and continued to update this plugin, it's especially friendly to some handles that use wired connections.

My Switch can't use the Xbox mode of the Chick T4 controller
syscon version 1.1.1
Switch version: 18.0.0.0
hekate version: 6.2.0
Atmosphere version: 1.7.2
I think some other controllers should have the same Xbox mode as the Xbox controller when in use

I know it's not easy to develop, and my Atmosphere Mop has integrated your plugin, and I'll be with you until you abandon the project

**Comment by o0Zz** [comment]
Did you follow this https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md ? If yes, please provide the logs

**Comment by Zhuwenxue2002** [comment]
Of course, I've added the controller to the config file, but instead of mapping the keys one by one, I've used the Xbox360 configuration file



My Tesla plugin becomes stuttered after inserting the handle, how do I provide you with the logs? Is the log recorded automatically Do I just need to look at the log file in the config

**Comment by o0Zz** [comment]
https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs

**Comment by Zhuwenxue2002** [comment]
|I|00:22:28.337|1CB47210| New USB device detected, checking for controllers ...
|I|00:22:28.348|1CB47210| Trying to initialize USB device: [2f24-0050] (Class: 0xFF, SubClass: 0xFF, Protocol: 0xFF, bcd: 0x0100)...
|E|00:22:28.727|1CB47210| No buttons configured for this controller [2f24-0050] - Stick might works but buttons will not !
|I|00:22:28.739|1CB47210| Initializing Generic controller (Interface count: 1) ...
|I|00:22:28.751|1CB47210| GenericHIDController USB joystick successfully opened (1 inputs detected) !
|I|00:22:28.762|1CB47210| SwitchHDLHandler Initialized !
|E|00:22:28.772|1CACA000| SwitchUSBEndpoint: Read returned no data !
|E|00:22:28.785|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.797|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.809|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.821|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.834|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.846|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.858|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.870|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.882|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.895|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.907|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.919|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.931|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.944|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.957|1CACA000| GenericHIDController Failed to parse input data
|E|00:22:28.969|1CACA000| GenericHIDController Failed to parse input data
![image](https://github.com/o0Zz/sys-con/assets/56246634/b98081d2-3e9f-485e-842c-7233e3fb8794)

**Comment by o0Zz** [comment]
Ok try:

[2f24-0050]

"F" have to be lowercase, let me know if it's better

**Comment by Zhuwenxue2002** [comment]
oh I found it, hahahahaha has succeeded
Thanks a lot, I'll close this issue

**Comment by o0Zz** [comment]
great, I will make the sys-module more resiliant to this kind of typo. Thanks
