### ISSUE TITLE
XBOX 360 controller not working

### ISSUE THREAD

**Issue by adriman22** [o0Zz/sys-con#18]
**Information**
Atmosphere version: 1.7.0
Switch OS version: 1.8.0.0
Syscon version: 1.2.1-ATMOSPHERE-1.7
Controller: Xbox 360 special edition transforming dpad controller

**Description**
I conect the controller to the switch with the wire, but the controller leds keep on blinking (like pairing mode) and never conect, enable the "log_level=0" but no errors, seems like it doesn't even know the controller is conected, i read all proyect issue and Troubleshooting from the original proyect and this one, tried everything but nothing seems to work, it simply keeps on blinking and nothing apears in the logs

**Logs**
[logs.zip](https://github.com/user-attachments/files/15929159/logs.zip)

**Comment by o0Zz** [comment]
Interresting. I have multiple xbox360 controllers and I never met this issue. There is a kind of similair issue with a XboxS here: https://github.com/o0Zz/sys-con/issues/14#issuecomment-2174383419
BoLThompson mention is has to first power on the controller before connecting the USB cable. Did you try this ?
Because you are right, the switch don't reconize at all your controller like if the control don't have data on usb cable. Did you try to plug the same controller and same cable to a PC, what's happen ?

**Comment by thierryquemerais** [comment]
Any update on this ticket ?

**Comment by adriman22** [comment]
Sorry, didn't read your message, not in home right now, I will update you in a few hours

**Comment by adriman22** [comment]
Just tested with windows and seems like is doing the same, the led keep on blinking but no response.

Also tested with first powering the controller and then conecting and power + pairing and then conecting, but nothing seems to work... 

It shows in the device manager at least so it's doing something but the led just keep on blinking, never truly paired

Device manager (im spanish by the way):
![image](https://github.com/o0Zz/sys-con/assets/39993602/78776768-fd67-4cd7-b33e-7deca810a6c9)

The controller:
![image](https://github.com/o0Zz/sys-con/assets/39993602/8365c6e9-634c-4396-821c-b5c71e1395c3)

**Comment by o0Zz** [comment]
Ok, and what's happen on your pc when you go in "joy.cpl" tool ?  do you see your controller and can you see your input ?

**Comment by adriman22** [comment]
It doesn´t even appear... seems like my xbox 360 controller is dead or something... just tested the swich with a ps1/2 controller and worked just fine

![image](https://github.com/o0Zz/sys-con/assets/39993602/a8f3bfd2-5483-4a48-aa09-b8e3f8d855e9)

**Comment by o0Zz** [comment]
Yeah that was my assumption. You controller seems to behave exactly if it was in wireless and not trying to connect to usb. SO, either the USB cable is not working or the controller USB part is not working. If you have a wireless received USB for xbox360, it might works.

**Comment by o0Zz** [comment]
Or maybe you have to switch your xbox360 wireless controller from wireless mode to usb mode ? By pressing sync button ? or other ? Try to look on internet if you see any help on this. You have to find a way to plug your controller to your PC, once you havethis working on your PC it will work with your switch.
