### ISSUE TITLE
Cosmic Byte Xbox360 controller not working

### ISSUE THREAD

**Issue by vbspk** [o0Zz/sys-con#25]
Thanks in advance for giving a new life to this project.

**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.2.2
Controller: Cosmic Byte Xbox360 controller wired controller

**Description**
The controller is powered on but not connecting to the console. The logs for the controller pid-vid(045e-028e) Reports an error "Failed to acquire USB interface -  - Error: 0x25A8C (Module: 0x8C, Desc: 0x12D) !
". I could see the same pid-vid present in the config file, so didn't add new entry.
I also disabled mission control form hekate-toolbox and rebooted my console.
I am able to use this controller on windows 11 laptop.
[log[1].log](https://github.com/user-attachments/files/16353826/log.1.log)

**Comment by o0Zz** [comment]
Hi,
There is something incorrect in your configuration I think, from the log we can see:
```
|I|00:01:39.322|6194A0D0| Initializing Generic controller (Interface count: 1) ...
```

Which means sys-con try to load your controller as "generic" controller and not xbox360 that probably the issue.

Try to add `profile=xbox360` in the section `[057e-2009]` and let me know the result

**Comment by vbspk** [comment]
Hi @o0Zz ,

I was also confused to see why its printing different id (057e-2009) initially. I found that this id corresponds to switch pro controller(Attached screenshot for your reference). After a while it switches from this id to (045e-028e), not sure why. I am also attaching the screenshot from windows control with hardware id of the controller.

Anyways i changed the config.ini by adding this id with xbox360 profile. Still its not working.

[ConfigAndLogs.zip](https://github.com/user-attachments/files/16359238/ConfigAndLogs.zip)

**Comment by vbspk** [comment]
Hi @o0Zz ,

I just tried changing the discovery mode from 0 to 1 and its working. Looks like my controller has option to switch its behavior when its connected to pc and switch, never thought this cheap 15$ controller would be compatible with switch. So to use other 3rd party controllers along with this one i have to add the vids manually in the config right..? Or do I have to do more changes..?

**Comment by o0Zz** [comment]
I didn't know controllers could do that (switch on the fly from switch to xbox360).
In any case. you're right, if you can't force this controller to stay in xbox mode then you need to set discovery mode to 1 and provide a list of vid-* you want to support. Theoretically discovery=1 will support all xbox360 controllers + the list you provide and according to what I saw there is a very hudge number of controllers that simulate the xbox360 so there is a big chance most of the controllers you plug in will works.

**Comment by vbspk** [comment]
Ok, good to know that all xbox360 controllers are supported.
Thanks a lot for all the help.
