### ISSUE TITLE
New Xbox adapter?

### ISSUE THREAD

**Issue by eaglezoli** [o0Zz/sys-con#29]
Hey, I know it works with the 360 adapter but what about the new one? Thanks!

**Comment by o0Zz** [comment]
I'm not sure to understand the question, could you please provide a complete context + provide an explanation + provide picutre and all what is needed to understand the question. Thank you

**Comment by rferizoli** [comment]
Hey,

So I saw sys-con supports the 360 adapter:
![IMG_0358](https://github.com/user-attachments/assets/c874be88-e1f5-4b38-9682-230059d14162)

That’s this one right, which is the original adapter:
![IMG_0359](https://github.com/user-attachments/assets/d01c9025-a501-43af-8cbe-009c8aec8ea0)

But what about the newer adapter, which is for the Xbox one/series controllers:
![IMG_0360](https://github.com/user-attachments/assets/08656d10-84bc-4685-ad4f-8efe2087000e)

Thanks!

**Comment by o0Zz** [comment]
Ok thank you for the precision. So I personnaly didn't try it but there is a good chance to works. Right now, nobody reported issue with this controller. Try it and let us know ;)
