### ISSUE TITLE
Thrustmaster Dual Analog 4 sticks not working

### ISSUE THREAD

**Issue by charlye30** [o0Zz/sys-con#32]
**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.3.0
Controller: Thrustmaster Dual Analog 4

**Description**
Hello. I got my controller working remaping the buttons, but the two sticks are not working and I don't know what to do. The rest of buttons work. "Calibrate control sticks" on console settings don't work also. Thank you in advance.

My gamepad is in the known_gamepads.txt of the branch project, is called "044f:b315 ThrustmasterDualAnalog"

**Logs**
Log file
[log.log](https://github.com/user-attachments/files/16650498/log.log)
Config.ini file
[config.ini.txt](https://github.com/user-attachments/files/16650502/config.ini.txt)

**Comment by o0Zz** [comment]
hum It's curious. Did you try your controller on windows ? When you go in "joy.cpl" do you see your controller stick moving ?

**Comment by charlye30** [comment]
> hum It's curious. Did you try your controller on windows ? When you go in "joy.cpl" do you see your controller stick moving ?

Yes it works. with the config.ini without configuration (stock) sticks goes down all the time but I can move it up and down but there still going down.

Stock(mapping incorrect, sticks work but bad, going down all time but I can move up and down):
[044f-b315] 
b=1
a=2
x=3
y=4
l=5
r=6
zl=7
zr=8
minus=9
plus=10
capture=11
home=12
lstick_click=13
rstick_click=14

My edit(fix button mapping, adding right_stick_x=Z and right_stick_y=Rz makes sticks don't work):
[044f-b315] 
b=1
a=3
x=4
y=2
l=5
r=7
zl=6
zr=8
minus=9
plus=10
simulate_home=minus+plus
right_stick_x=Z
right_stick_y=Rz

**Comment by o0Zz** [comment]
Could you please send a screenshot of your windows joy.cpl when the controller is connected to it (Do not touch any button)

**Comment by charlye30** [comment]
> Could you please send a screenshot of your windows joy.cpl when the controller is connected to it (Do not touch any button)

![aa](https://github.com/user-attachments/assets/c7a5383b-f58a-40a2-9bc4-6fa32f055f6b)

**Comment by o0Zz** [comment]
Ok. according to the screenshot it seems you installed a driver on your Windows.
Could you remove the driver you installed on your PC and check if it still works fine ? 
Then resend a snapshot please

**Comment by charlye30** [comment]
> Ok. according to the screenshot it seems you installed a driver on your Windows. Could you remove the driver you installed on your PC and check if it still works fine ? Then resend a snapshot please

![Untitled](https://github.com/user-attachments/assets/74e37ffa-7a59-4cc2-989d-c43c4f541968)

now is like this, thank you

**Comment by o0Zz** [comment]
Ok great. Ok tha't the first time I see "Slider" (Ussually it's Z Axix) So, for Z Rotation it's Rz on the switch, so try to determine with windows if Rz if for X or Y on your controller. I will try to check what means "Slider", Could you enable log trace on the switch (log_level=0) reboot the switch, and send me the logs once you plug your controller to the switch. Thanks

**Comment by o0Zz** [comment]
Ok try this version, it should fix your issue (Right stick X & Y might be reversed because I have no way to test it - If this is the case edit the config.ini and reverse Rz with Slider) - Use the config.ini from this version (And remove yours). 
Let me know the result. 
Thanks

[sys-con-1.3.0+1-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16651899/sys-con-1.3.0%2B1-ATMOSPHERE-1.7.x.zip)

**Comment by charlye30** [comment]
> Ok great. Ok tha't the first time I see "Slider" (Usually it's Z Axis) So, for Z Rotation it's Rz on the switch, so try to determine with windows if Rz is for X or Y on your controller. I will try to check what means "Slider", Could you enable log trace on the switch (log_level=0) reboot the switch, and send me the logs once you plug your controller to the switch. Thanks

Sorry I don't understant well your message.
The log file in my main message is okay or you want another one?

X axis / Y axis is for the left stick
slider / rotation is for the right stick

https://github.com/user-attachments/assets/74991e7f-6b63-41cf-9789-ae8c106ff464

**Comment by charlye30** [comment]
> Ok try this version, it should fix your issue (Right stick X & Y might be reversed because I have no way to test it - If this is the case edit the config.ini and reverse Rz with Slider) - Use the config.ini from this version (And remove yours). Let me know the result. Thanks
> 
> [sys-con-1.3.0+1-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16651899/sys-con-1.3.0%2B1-ATMOSPHERE-1.7.x.zip)

Thank you, I'm trying right now

**Comment by charlye30** [comment]
> Ok try this version, it should fix your issue (Right stick X & Y might be reversed because I have no way to test it - If this is the case edit the config.ini and reverse Rz with Slider) - Use the config.ini from this version (And remove yours). Let me know the result. Thanks
> 
> [sys-con-1.3.0+1-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16651899/sys-con-1.3.0%2B1-ATMOSPHERE-1.7.x.zip)
Tried without luck. I attach a video and log of the behavior. Thank you

https://github.com/user-attachments/assets/6aac0f23-6667-4ad1-b0cc-9f69a9ec0fe0

[log.log](https://github.com/user-attachments/files/16651949/log.log)

**Comment by o0Zz** [comment]
Ok indeed there is 2 issues. We fixed the first one with the slider and it looks fixed according to what I see in the logs, but now I can see another issue with min/max. I will provide you a fix tomorrow.

**Comment by o0Zz** [comment]
Hi,
Could you try this version, it's supposed to fixed the 2nd issue where min/max read are incorrects
Let me know if it solve your issue
Thanks
[sys-con-1.3.0+2-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16665252/sys-con-1.3.0%2B2-ATMOSPHERE-1.7.x.zip)

**Comment by charlye30** [comment]
> Hi, Could you try this version, it's supposed to fixed the 2nd issue where min/max read are incorrects Let me know if it solve your issue Thanks [sys-con-1.3.0+2-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16665252/sys-con-1.3.0%2B2-ATMOSPHERE-1.7.x.zip)

Now everything works!! Thank you lots!! 
The only issue (if there is a issue) is that the sticks in calibrate control sticks  the plus mark goes out the circle(making a square, not a circle), is this a problem? happens in both sticks.

https://github.com/user-attachments/assets/a774512c-88f4-4a54-9048-f9a7a4bb5cc8

**Comment by o0Zz** [comment]
Good news ;) You can use this version for now and this fix will be available in the next release (not planned yet).
 
Regarding the calibrate control sticks screen I think this is caused by your controller. I have few controllers on my side, and few of them do a circle on windows and some other do a square on windows. I think your do a square on windows and thus you have the same behavior on the switch (That make sense) I have 1 question: does it cause any issue to play any game ? thanks

**Comment by charlye30** [comment]
Good morning, just added " lstick_click=11 and rstick_click=12 " for made joystick left and right buttons work. Now everything works. Thank you.

> [044f-b315] ;Thrustmaster Dual Analog 4
> b=1
> a=3
> x=4
> y=2
> l=5
> r=7
> zl=6
> zr=8
> minus=9
> plus=10
> simulate_home=minus+plus
> rstick_left=-Rz
> rstick_right=+Rz
> rstick_up=+Slider
> rstick_down=-Slider
> lstick_click=11
> rstick_click=12

**Comment by o0Zz** [comment]
Thank you for this feedback, i will include it in the master branch.
