### ISSUE TITLE
Xbox 360 v2 blinking but not recognized

### ISSUE THREAD

**Issue by msteroreo1** [o0Zz/sys-con#33]
READ THE TROUBLESHOOTING GUIDE
Before posting a new issue, please make sure to first read the Troubleshooting guide: https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md

**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.3.0
Controller: [045e-028f] ;Microsoft X-Box 360 pad v2

**Description**
I tested the Xbox 360 v2 controller through cable but it only blinks and doesn't even get recognized in the controllers section.
I already tried the troubleshoot guide but nothing worked.

**Logs**
- Attach your logs /config/sys-con/log.log to the ticket "Trace" mode (https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs)
- Attach your /config/sys-con/config.ini

[Log.zip](https://github.com/user-attachments/files/16737210/Log.zip)

**Comment by o0Zz** [comment]
I think you are using a xbox360 wireless with a USB cable is it correct ? If this is the case then everything is normal, the xbox360 wireless controller don't have a USB connection, in fact the USB cable is only used for charging the controller.

**Comment by o0Zz** [comment]
Could you confirm you are trying to use a XBOX360 wireless controller ?

**Comment by msteroreo1** [comment]
Sorry, I didn't know it. I thought it was a data cable. It is a wireless controller. As it showed up in device manager I was convinced it was possible to use over USB.

**Comment by o0Zz** [comment]
I agree it's confusing, I will update the troubleshooting guide to avoid this error in the future.
