### ISSUE TITLE
Gamecube adapter BX-W201 not working

### ISSUE THREAD

**Issue by Tinky226** [o0Zz/sys-con#34]
First of all thanks for hard work!!

**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.4
Device: Gamecube adapter BX-W201

**Description**
 I am trying to use my GameCube controller with the BX-W201 adapter, but it doesn't work at all when SysCon is active. My version differs from the BX-W201C, as mine does not come with a WiiU/Switch/PC switch. Is there any way to make them work together? 

log:
[log.log](https://github.com/user-attachments/files/16830757/log.log)

config:
[config.txt](https://github.com/user-attachments/files/16830759/config.txt)

**Comment by texita** [comment]
Your adapter will only work in discovery_mode=1 you can set in the config file, simply switch the actual 0 to 1.

**Comment by o0Zz** [comment]
Texita is right, you need discovery_mode=1.

@texita Yes, we can add all these adapters to the https://github.com/o0Zz/sys-con/blob/master/doc/TestedControllers.md manual. 
But I'm not sure to understand why you said: "**all** adapters with VID/PID [057e-0337]".
Do you mean that all Gamecube to Switch adapters have this VID/PID? 
Like this one: HS-WU025, BX-W201C and WUP-028 all have VID/PID = [057e-0337]? Is what you means ?

**Comment by texita** [comment]
Yes, have a look in the screenshot of this post
https://github.com/o0Zz/sys-con/issues/2#issuecomment-2303647644
I've put a red square around it :)

**Comment by o0Zz** [comment]
Got it thanks, I updated the tested Controllers

**Comment by texita** [comment]
I've seen you have changed the adapters in pc mode aswell, the VID/PID 057e-0337 is valid only for original adapters (they come without pc mode) or adapters like tinky226 ones, that comes without pc mode aswell.
For the adapters in pc mode the VID/PID change, you can see  the differents VIDs/PIDs from this post: https://github.com/o0Zz/sys-con/issues/2#issuecomment-2184939448

So
![brave_u2E68Urjg0](https://github.com/user-attachments/assets/41d1d6b2-627a-445f-be85-fac617446a12)
