### ISSUE TITLE
Xbox 360 Wireless Receiver detected, but controller not working

### ISSUE THREAD

**Issue by SafalChapagain** [o0Zz/sys-con#35]
**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.4.0
Controller: XBox 360 Wireless controller (with USB wireless receiver)

**Description**
The wireless receiver is detected in the log, but my controller cannot sync to it. The 360 controller just blinks all 4 lights forever, even after pressing the sync button on both devices (it does the quick flashes of 4 lights so I know it's trying to sync but then just goes back to the 4 slow blinking lights instead of the 1 constant light). On my Windows PC it works fine, getting the one constant light on the top left. No buttons or analogue sticks work while the 4 lights are blinking,

**Logs**
[log.log](https://github.com/user-attachments/files/16908187/log.log)

Config is default with trace mode (and you can see it's trying to use profile xbox360w in log)

**Comment by o0Zz** [comment]
Good catch. It's a regression introduced in v1.4.0. 
This build should fix it.
[sys-con-1.4.0+6-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16912820/sys-con-1.4.0%2B6-ATMOSPHERE-1.7.x.zip)

**Comment by SafalChapagain** [comment]
Quite a coincidence that 5 days after the update I happen to install this and immediately find a regression 😛

Thanks for the quick fix, will test shortly

**Comment by SafalChapagain** [comment]
Looks good to me, although is there a reason that by default for xbox360w the minus and plus mappings are swapped compared to xbox360? It feels like it should be the same as xbox360, as for me plus is the back button and minus is the start button,

**Comment by o0Zz** [comment]
You are right, that's not expected. Xbox360 wireless looks incorrect. 
I updated the [config.ini](https://github.com/o0Zz/sys-con/blob/master/dist/config/sys-con/config.ini)
Xbox360 wireless controller is one of the first I worked on but I didn't tested it recently. ;) I will release a v1.4.1 with these fixed today.
