### ISSUE TITLE
Analogue joysticks deadzone low range

### ISSUE THREAD

**Issue by zerofalcon** [o0Zz/sys-con#36]
**Information**
Atmosphere version: 1.5.5 E
Switch OS version: 16.1.0
Syscon version: sys-con-1.4.1-ATMOSPHERE-1.6.x
Controller: Gamecube Controller Adapter BX-W201C

**Description**
Hi! first of all thanks for continue developing this great piece of software.
I know I'm using an old version of atmos+HOS but hear me out, sys-con (1.6.x rev) works fine even at that low firm/cfw versions.

The issue was described months ago on the discussions section, a guy noted how the analogue joystick of his n64 adapter-controller cant reach the full range while testing calibration, well, same happens to the gamecube adapter and gamecube controllers.

I´m using a wavebird controller with it, if I use the adapter in switch mode the calibration range reach at its fullest position, if I change to PC mode and use sys-con, the left joystick and C stick behave as if both cant reach maximum calibration, and btw, trying to calibrate by pressing the calibrate button it is not working, the stick doesnt even move to any direction . I recorded two videos to show how the issue performs with both scenarios.

Switch mode:
https://github.com/user-attachments/assets/d99ddf2a-e319-46a9-a18f-6980480d5180

PC Mode:
https://github.com/user-attachments/assets/c518db08-54db-4a15-8a31-91eeae6af9dc

Another noted issue was using the controller type in "n64" mode, if activated, C-buttons (using nso n64 switch online) are not working, i.e, the right stick and Y-X buttons becomes unusable with the n64 app.

Aside of that, everything works fine,  I can remap whatever can be remapped.
I hope a solution can be done as this is right now the only perfect module to remap usb controllers.
Thanks in advanced and keep up the good work!

P.D. I forgot to mention, I already made some tests changing the deadzone values to no avail. 

**Logs**
[log.log](https://github.com/user-attachments/files/17065956/log.log)
[config.txt](https://github.com/user-attachments/files/17065991/config.txt)

**Comment by o0Zz** [comment]
Hi, thanks for this detailed report.
I think I see the issue, not sure if it will cause any issue during gameplay but anyway it would be nice if sys-con can handle controller that cannot reach the switch range.
Here is a new version that allow to set a "factor" for analog input.

By default the factor is: 100 for 100%, for your controller I set it to 110% (maybe you will need to increase this value). Let me know if it helps 
[sys-con-1.4.1-ATMOSPHERE-1.6.x.zip](https://github.com/user-attachments/files/17088550/sys-con-1.4.1-ATMOSPHERE-1.6.x.zip)

PS: Copy everything (including the configuration file)

**Comment by zerofalcon** [comment]
Hi! thank you so much for fixing the analog switch range issue. I had to adjust the factor to 150 (wavebird joystick its the oem one, very very used) and now the stick and C-stick reaches the full range, giving great results for n64 emulation/other switch games. If any more tests are need to be done I have everything ready to test.

Once again thanks for making this module the best for the switch!

**Comment by o0Zz** [comment]
Hi, Good to hear it fix your issue. Could you share your new configuration, is it like that ?
```
[0079-1846] ;GC controller adapter BX-W201C (pc mode)
controller_type=gamecube
b=3
a=2
x=1
y=4
l=5
r=6
zr=8
plus=10
dpad_up=13
dpad_right=14
factor_x=150
factor_y=150
```
Thanks
