### ISSUE TITLE
Support For Atmosphere1.8.0

### ISSUE THREAD

**Issue by FTWx123** [o0Zz/sys-con#38]
please Support For Atmosphere1.8.0

**Comment by FTWx123** [comment]
I've tried the latest version, but when I get into the atmospheric system, the picture below comes up.
![IMG_20241014_113039](https://github.com/user-attachments/assets/fca9c010-1da6-40dc-a141-7353288566a5)

**Comment by FTWx123** [comment]
atmosphere prerelease version has updated. when will the sys-con get updated?

**Comment by o0Zz** [comment]
I was waiting for atmosphere to officially release it. So if it's done, it will be probably done this evening or tomorrow.

**Comment by o0Zz** [comment]
Could you let me know if this version works on your side.
I still have some work to do on it but wanted to validate the starting point works. Thanks

[sys-con_atmosphere1.8.zip](https://github.com/user-attachments/files/17402889/sys-con_atmosphere1.8.zip)

**Comment by FTWx123** [comment]
I have tried two versions in the compressed file, but when I entered the atmospheric system, a crash occurred![IMG_20241017_075901.jpg](https://github.com/user-attachments/assets/1c8f0754-904d-47d7-b8a4-342e4f6719ab)

![IMG_20241017_075856.jpg](https://github.com/user-attachments/assets/c256f208-c599-4531-963c-b01f0080adb3)

**Comment by rashevskyv** [comment]
Confirm. Not working on 19.0.0. Same error

**Comment by o0Zz** [comment]
Thanks for the tests, let try this one -> 

[sys-con-1.4.1+10-ATMOSPHERE-1.7.x-1.8.x.zip](https://github.com/user-attachments/files/17421945/sys-con-1.4.1%2B10-ATMOSPHERE-1.7.x-1.8.x.zip)

**Comment by FTWx123** [comment]
it work thanks

**Comment by o0Zz** [comment]
sys-con 1.4.2 has been release for atmosphere 1.8 support.
