### ISSUE TITLE
not working for my third part controller 

### ISSUE THREAD

**Issue by fengsuxing** [o0Zz/sys-con#40]
[Desktop.zip](https://github.com/user-attachments/files/17399219/Desktop.zip)
not working,i configed follow the readme. i can see device in log file,but cant see it in switch.i pressed all key in controller,not working`

**Comment by pokeyjojo** [comment]
Hey i have the same issue on the recently released 8bitdo lite se 2.4g (controiller shows up but no inputs do anything) here is my log (the failed to parase the .ini file was when i forgot a [ when i was trying to use the windows pc to configure my controller
[log.log](https://github.com/user-attachments/files/17403610/log.log)

**Comment by pokeyjojo** [comment]
unlike op the controller shows up on switch, just no inputs

**Comment by o0Zz** [comment]
@pokeyjojo  could you please open a new ticket and provide the log in debug - That's a differnt issue

**Comment by fengsuxing** [comment]
> Hi,
> 
> Could you please describe the issue a bit more ? Could you provide the controller model your are using and provide what's happen exactly ?
> 
> According to the logs, your controller works properly and is properly detected by the switch. Sometime you got some error like: 0x25A8C meaning the switch opened this controller before sys-con. Do you have another driver installed like MissionControl ?
> 
> At the begining of the file I think your controller was properly detected by the switch, while at the end it was not able to detect it. Is it correct ?
> 
> Thanks

no ,its not work at the begining,I can't find my controller on tv screen(switch).as you see ,it only work fine in log....
ps  ( Sometime error is that  I replug in the controller on usb )，I THINK SOMETIME ERROR is not important，solve the log OK,screen not working ISSUE will be OK.


https://item.jd.com/1755629.html this is my model callled 北通 蝙蝠2

**Comment by fengsuxing** [comment]
i already configed ini by windows pc

**Comment by o0Zz** [comment]
Nice catch, after your 2nd feedback I add a better look and you are right, something is wrong in sys-con. 
Try this build and let me know if it fix you issue

**Comment by fengsuxing** [comment]
great! its working now!!!  what's the problem?i'm curious

> Nice catch, after your 2nd feedback I had a better look and you are correct, something is wrong in sys-con with this controller. Try this version and let me know if it fix your issue: [sys-con-1.4.2+1-ATMOSPHERE-1.7.x-1.8.x.zip](https://github.com/user-attachments/files/17440048/sys-con-1.4.2%2B1-ATMOSPHERE-1.7.x-1.8.x.zip)

**Comment by o0Zz** [comment]
Great to hear it’s working! Your controller exposes multiple profiles (e.g., mouse, joystick, etc.). The joystick is in the second position, but the issue occurred because sys-con tried to access it in the first position (sys-con was using the wrong index). As a result, while sys-con was receiving data from the controller correctly, it wasn’t reporting it to the Switch.
