### ISSUE TITLE
Adaptive 8bitdo lite se 2.4g appears in switch but no inputs register 

### ISSUE THREAD

**Issue by pokeyjojo** [o0Zz/sys-con#41]
**Information**
Atmosphere version: 1.8.0
Switch OS version: 18.1
Syscon version: 1.4.1
Controller: 8bitdo lite se 2.4g

**Description**
Title says it. The controller appears but nothing happens on any inputs. same problem on ams 1.7.0 and the logs seem like everything is working but its just not
**Logs**
- Attach your logs /config/sys-con/log.log to the ticket "Trace"
 mode (https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs)
[config.ini.txt](https://github.com/user-attachments/files/17404609/config.ini.txt)

- Attach your /config/sys-con/config.ini
[log.log](https://github.com/user-attachments/files/17404596/log.log)

**Comment by o0Zz** [comment]
Ok I think it's the same issue than pdp controllers.
Some xboxone controller expect a specific boot sequence (That's happen with xboxone controller) Do you have a linux to check if this controller works on linux ? (sys-con do the same boot sequence than the official xpad linux driver, so, my assumption is, if it doesn't works with sys-con it should not work on linuxtoo.)

I will probably need a wireshark capture to understand to boot sequence and reproduce it.
Could you please provide a wireshark capture ? -> https://github.com/o0Zz/sys-con/blob/master/doc/WiresharkCapture.md
Thanks

**Comment by pokeyjojo** [comment]
i cant test on linux atm but here are the captures, one wired and one with the 2.4g reciever that came with the controller 
[8bitdocapture.zip](https://github.com/user-attachments/files/17424209/8bitdocapture.zip)

**Comment by o0Zz** [comment]
Thank for the wireshark capture. You found a regression in sys-con, try this version and let me know if it fix the issue.
[sys-con-1.4.2+2-ATMOSPHERE-1.7.x-1.8.x.zip](https://github.com/user-attachments/files/17440107/sys-con-1.4.2%2B2-ATMOSPHERE-1.7.x-1.8.x.zip)

**Comment by pokeyjojo** [comment]
hello. this new build, now pressing the guide button works but none of the other buttons do anything, here is my log
[log.log](https://github.com/user-attachments/files/17441102/log.log)

**Comment by pokeyjojo** [comment]
i could also press and hold it to open the quick menu with sleep mode and airplane mode options

**Comment by o0Zz** [comment]
Great, we're making progress on the issue. If this build doesn't work, we'll need to iterate further. You've already provided the boot sequence, and based on that, I’ve tried to isolate the part responsible for initializing the controller. This build reflects those changes. If it still doesn’t work, we may need to go back and forth to pinpoint the correct sequence.

[sys-con-1.4.2+3-ATMOSPHERE-1.7.x-1.8.x.zip](https://github.com/user-attachments/files/17443217/sys-con-1.4.2%2B3-ATMOSPHERE-1.7.x-1.8.x.zip)
