### ISSUE TITLE
Gamepad overrides Switch Lite input

### ISSUE THREAD

**Issue by chromebo** [o0Zz/sys-con#44]
**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.0
Syscon version: latest
Controller: unnamed

**Description**
Hi, please help me!
The gamepad correctly connected to the Switch Lite, but during tests in the Mario Party game it turned out that the gamepad overrides the Switch Lite input. I thought it would be possible to play two players: one on the console, the other on the gamepad. However, this is not the case.

UPD1:
Okay, I realized that the problem lies in the "Change Grip/Order" built into the original system. If a game accesses it (such as Mario Party), then input from Switch Lite is not taken into account there. I noticed something else in Binding of Isaac, which allowed me to add players bypassing the "Change Grip/Order". She just didn't call him, from the gamepad you just had to press the start button and that was it.

UPD2:
I found out that the previous assumption is true, after trying several Nintendo games, none of them could be played in the desired way, because everyone uses "Change Grip/Order". Some NON-Nintendo games fully supported simultaneous input from Switch Lite and gamepad. I can't even imagine how to solve this problem. Yes, I understand that it is no longer related to sys-con at all.

is it possible to try using the homebrew application to emulate input from Switch Lite as from a separate gamepad?

**Logs**
Here i tried connect gamepad and console input into Mario Party
[log[1].log](https://github.com/user-attachments/files/17446973/log.1.log)

**Comment by o0Zz** [comment]
Hi,
I think this limitation has been introduced by nintendo to differentiate the lite vs normal switch. They probbaly want to make sure people will not use the lite to play with multiple people.

I don't think we can emulate the switch lite gamepad. You can try on your side to play with "controller_type=" to see if it change something but I don't think it will solve anything.

Maybe there is a way to patch the kernel or to change this bahavior but clearly that's not the intent of sys-con here.
