### ISSUE TITLE
Module does nothing

### ISSUE THREAD

**Issue by Zouizoui78** [o0Zz/sys-con#46]
**Information**
Atmosphere version: 1.8.0
Switch OS version: 19.0.0
Syscon version: 1.4.3
Controller: Generic USB controller / Xbox one controller

**Description**
Just nothing happens. I extracted the release file at the root of the SD card and checked that all the files are at the right place.
When I plug a controller it doesn't work and no log file is created, as if the plugin was not running.

Any idea how to troubleshoot that ? I'm pretty sure I made a mistake somewhere but since the install process is very easy I'm not sure where 😅 maybe there's some general sysmodule logs somewhere ?

**Logs**
No log (see description)

**Comment by o0Zz** [comment]
Could you try v1.4.2 to check if its a regression on the last binary or a setup issue on your side.
