### ISSUE TITLE
Please add my controller to the update list.

### ISSUE THREAD

**Issue by Bigclam04** [o0Zz/sys-con#47]
Please add my controller to the update list. My controller name is bigbigwon BLITZ2.
![IMG_9068](https://github.com/user-attachments/assets/5c6e2a76-90ba-4e8a-8871-b5de8255fe56)

**Comment by o0Zz** [comment]
Sorry we don't do that. You have todo it by yourself. There is lot of documentation in this repository to so it. You dont need to code just to read documentation and change the config file
