### ISSUE TITLE
Logitech G920 - Not Seen - No logs generated

### ISSUE THREAD

**Issue by tadthies** [o0Zz/sys-con#48]
READ THE TROUBLESHOOTING GUIDE
Before posting a new issue, please make sure to first read the Troubleshooting guide: https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md

**Information**
Atmosphere version: 1.7.x-1.8.x
Switch OS version: 19.0.0
Syscon version:  1.43
Controller: Logitech G920
Nintendo Switch – OLED Model

**Description**
I get no functionality of the wheel or pedals on the switch.   i enabled logging at all the different levels, and no logs were produced.  not even a empty log file.  The steering wheel does it inital calibration when the switch is powered up with it plugged in, or when you plug it in to the switch that ios aleredy on.   Nothing else.
i tried booting the switch with the wheel plugged in as well as pluging the wheel in with the switch already on.
i tried adding the diffrent drivers in the config file as well,

**Logs**

No logs were generated,  tried all the different logging levels.

- Attach your logs /config/sys-con/log.log to the ticket "Trace" mode (https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs)
- Attach your /config/sys-con/config.ini

**Comment by o0Zz** [comment]
If there is no logs, it means sys-con is not loaded. Sys-con generate a log whatever happen. Look at a similar issue: #46 . You need to understand what block sys-con from your setup.(or maybe installation issue)

**Comment by o0Zz** [comment]
In can it helps: https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md#i-dont-see-any-logs-in-configsys-conloglog
