### ISSUE TITLE
Inquiry on Reducing Input Lag for Third-Party Controller in Apex Legends


### ISSUE THREAD

**Issue by FTWx123** [o0Zz/sys-con#49]
I hope this message finds you well. I am currently using your syscon plugin on my Nintendo Switch and I'm enjoying the enhanced gaming experience it provides. However, I've encountered an issue while playing Apex Legends.

I've noticed that there is a significant input lag when using my third-party controller. This lag affects my gameplay, especially in fast-paced scenarios where quick reactions are crucial. I was wondering if you could provide some guidance or suggestions on how to reduce the input delay for my third-party controller while playing Apex Legends.

My controller is DualSense Edge

**Comment by o0Zz** [comment]
Hi,

Interresting issue, the polling frequency of sys-con is 1ms (thus 1000 hz) which is a lot more than any controller. Thus the limitation is more on controller sides that are not be able to provide information at such frequency.

1- Could you please confirm that you didn't enable debug logs ? (Check if log_lvl=2 or more)
2- Could you check with another controller to see if you have the same issue (for example a wired controller ?)

The idea is to check here if it's an isolated issue with DualSense or if it's a more general issue.

If some other player have the same feeling, please post your comment in this ticket.

**Comment by FTWx123** [comment]
Thank you for your prompt response and valuable insights.

I confirm that in my config settings, the log_lvl is indeed set to 2, and I have not made any changes to this setting.

Regarding the testing with other controllers, I understand your suggestion. I will experiment with a different controller to see if the input latency issue persists.

As for my main concern, I am looking for advice on how to reduce input latency during frame drops. Specifically, in complex scenarios like face-to-face combat in Apex Legends, I notice what seems to be increased input latency. I'm curious if there are any specific settings or optimizations that can help minimize this latency during such situations to enhance the gaming experience.

**Comment by ndeadly** [comment]
> the polling frequency of sys-con is 1ms (thus 1000 hz) which is a lot more than any controller

I would be surprised if you're actually achieving a 1ms polling interval. I've done some measurements of various controllers/input paths and USB delay is pretty bad (though I'll admit I haven't measured with sys-con, it's possible the performance I saw is partly due to the polling interval Nintendo uses for USB)

![current_standings](https://github.com/user-attachments/assets/de3fb62e-9b65-4b7d-8725-85242c8683bf)

> polling_thread_priority allow you to change the priority of the polling thread, you can try to set it on the maximum (63) and see what's happen. I do not warranty any result, but you could try (The default value is 48)

Thread priorities are inverted (lower number = higher priority). [This](https://switchbrew.org/wiki/System_Thread_Priorities) is incomplete/outdated, but you get the idea.

**Comment by ndeadly** [comment]
> Sys-con doesn't receive data at a frequency of 1000 Hz, but it does poll the USB interface every 1 ms to check for new data. The controller's polling frequency is clearly determined by the controller's specifications. I haven't benchmarked sys-con's read rate against a standard PC, but I didn't notice any significant difference during development.

What I meant was that even if a controller hypothetically had data ready for you every 1ms, I doubt the console can receive and process it that fast based off the data I collected. I would be curious to measure that at some point when I find the time.

> I also wonder if using HdlsVirtualDevice instead of hooking directly the interface could introduce extra latency.

It's probable. You've got an extra IPC call in the pipeline to update the state (in addition to `usbHsEpPostBufferAsync` and `usbHsEpGetXferReport`). Bluetooth switched from an IPC call to shared memory in firmware 7.0.0, so presumably IPC makes an impact on the latency. Whether it's enough to make a tangible difference is yet to be seen.

> I'm considering switching to a new implementation (to support rumble) in the next few month

FYI I already have a 90% complete implementation based around a usb mitm. Your time is probably better spent contributing to Mission Control ;)

> from what I understand, the input latency increases depending on what's happening in the game

We are sharing CPU core 3 with all the other system (and homebrew) services after all. I observed some time ago that Mission Control was adding ~5% CPU load for each connected controller.

**Comment by ndeadly** [comment]
> I hope this message finds you well. I am currently using your syscon plugin on my Nintendo Switch and I'm enjoying the enhanced gaming experience it provides. However, I've encountered an issue while playing Apex Legends.
>
> I've noticed that there is a significant input lag when using my third-party controller. This lag affects my gameplay, especially in fast-paced scenarios where quick reactions are crucial. I was wondering if you could provide some guidance or suggestions on how to reduce the input delay for my third-party controller while playing Apex Legends.

@o0Zz you might also want to clarify we are actually talking about USB here (I often get people mistakenly reporting USB issues on my repo, so I imagine it happens the other way too). Dualsense controllers appear to be more prone to RF interference and I've had people reporting _bluetooth_ input lag issues with them on multiple occasions

**Comment by o0Zz** [comment]
@FTWx123 per ndeadly suggestion, could you confirm that you are using ps controller with a wired cable with sys-con and not ps controller wireless with missioncontrol ?

**Comment by o0Zz** [comment]
> @FTWx123 per ndeadly suggestion, could you confirm that you are using ps controller with a wired cable with sys-con and not ps controller wireless with missioncontrol ?

@FTWx123 Any update on that ?
