### ISSUE TITLE
Hori battlepad [0f0d-00dc] home button

### ISSUE THREAD

**Issue by texita** [o0Zz/sys-con#5]
This is the pad:
https://stores.horiusa.com/battle-pad-zelda-for-nintendo-switch/
Pad sheet:
https://drive.google.com/file/d/1MtEB_cYm9Ju0I_w4vi6G1QiJRsrWL8BP/view?pli=1

The pad is already present in the original config.ini downloaded
[0f0d-00dc] ;HORIPAD FPS for Nintendo Switch
profile=xbox360

i solved the inverted buttons problem (swap A with B, swap X with Y) changing the xbox360 configuration

[xbox360]
driver=xbox360
B=2
A=1
Y=4
X=3
L=5
R=6
ZL=0
ZR=0
minus=7
plus=8

But i can't have the home button working, in the original sys-con it was working, the pad was loaded with the x360 drivers aswell.

it would be nice to have the screenshot button working aswell, but i think it will never work if the pad is loaded with x360 drivers.

maybe like Jayacheal said here https://github.com/o0Zz/sys-con/issues/2#issue-2334445562 a feature to load the orginal drivers? So even the rapid fire and all the functions will work :)

**Comment by o0Zz** [comment]
Yes absolutly I think it will be better to ignore this controller like mentioned in #2. This is a feature I'm working on. Regarding home button it's a general issue I missed to implement it. I did a patch, so it will be available in v1.0.3

**Comment by o0Zz** [comment]
Beside that i'm interrested to know how many buttons are detected on windows ? Do you have 11 buttons or more ?

**Comment by texita** [comment]
![IMG_20240606_133803.jpg](https://github.com/o0Zz/sys-con/assets/1828679/289b664f-f9be-4f16-8773-4bfdbf6708fc)

10 buttons, where ZL and ZR are the Z axis.

**Comment by o0Zz** [comment]
Thank you for the information. Yes I think both will be possible at the end. 

For your question yes its possible, indeed you are right the documentation is not clear on this point, I just updated it -> https://github.com/o0Zz/sys-con?tab=readme-ov-file#config

Let me know if it's more clear.

**Comment by o0Zz** [comment]
The original issue "Home" button has been fixed in the latest release -> https://github.com/o0Zz/sys-con/releases/tag/1.1.0
If you have another issue please open a new ticket. 
Thank you

**Comment by texita** [comment]
After a lot of testing this controller in discovery_mode=0 and discovery_mode=1 i think that it's should be better to change the default configuration of this pad to respect the hardware buttons to have a better continuity with all the switch, with atmosphere and originals , at the end it's better to relay on the controller original feature to swap L with ZL and R with ZR.
So i changed the config like this:

[0f0d-00c1] ;Hori battlepad (switch mode)
b=2
a=3
x=4
y=1
l=<del>7</del> 5
r=<del>8</del> 6
zl=<del>5</del> 7
zr=<del>6</del> 8
minus=9
plus=10
capture=14
home=13
lstick_click=11
rstick_click=12

but i've got a problem when this pad get recognized as xbox360, i can't map L or R they are always seen as ZL and ZR.

this is the configuration i've tried first
[0f0d-00dc] ;HORIPAD FPS for Nintendo Switch
profile=xbox360
B=2
A=1
Y=4
X=3
L=0
R=0
ZL=5
ZR=6

also tryed
L=Rx
R=Ry

but nothing changed, what i'm doing wrong for you?

**Comment by o0Zz** [comment]
Regarding first comment, ok we can switch Zl / L Zr/R. I don't really mind.

Regarding 2nd issue, could you provide the logs in trace mode (log_level=2) and could you press L / R and release it then press Zl / ZR then release (Do not forget the polling frequency is 500ms thus stay pressed for ~1s). I will check in logs if the data provided by the controller are the same for ZL/ZR and L/R.

**Comment by o0Zz** [comment]
Ok I think I understood the problem, could you try this:
```
ZL=5, None
ZR=6, None
L=Rx
R=Ry
```

**Comment by texita** [comment]
it's working with your configuration!
Yes, it was not a real problem, but had to use the pad toggle to many times between consoles, i think by default is the right thing by default to match the hardware layout (like we did for the playstation pads) anyway, in the end these are the configs for this pad:

[0f0d-00c1] ;Hori battlepad (switch mode)
b=2
a=3
x=4
y=1
l=5
r=6
zl=7
zr=8
minus=9
plus=10
capture=14
home=13
lstick_click=11
rstick_click=12

[0f0d-00dc] ;HORIPAD FPS for Nintendo Switch
profile=xbox360
B=2
A=1
Y=4
X=3
ZL=5,None
ZR=6,None
L=Rx
R=Ry

**Comment by o0Zz** [comment]
Ok great, I updated these controllers. 
Regarding the "None", in fact this is a bug introduced in the last versions. Could you try this version:

[sys-con-1.3.0+10-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16776923/sys-con-1.3.0%2B10-ATMOSPHERE-1.7.x.zip)

This is the same version you have with a bug fix and the config.ini updated with your latest changes (But without the need of the ",None")
Let me know if you get the same result.

**Comment by texita** [comment]
Tested 1.3.0+10, i confirm it's working without "None"
