### ISSUE TITLE
Controller with hybrid modes does not get detected/gets detected incorrectly

### ISSUE THREAD

**Issue by zionhian** [o0Zz/sys-con#56]
READ THE TROUBLESHOOTING GUIDE
Before posting a new issue, please make sure to first read the Troubleshooting guide: https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md

**Information**
Atmosphere version: 1.8.0
Switch OS version:  19.0.0
Syscon version: 1.4.3
Controller: PS(R) Gamepad Adaptor

**Description**
Appears to be a regression, but not necessarily with sys-con as I updated Atmosphere, sys-con and switch os all at once (syscon was on version 1.0 I believe)
Worked just fine in the previous version, but in this version it seems to catch the wrong profile (as the VID and PID in the logs appears of the generic PS3 controller). All previous devices I used seem to work just fine. I was not able to find the controller online anywhere, but it does have a playstation 2 connector at the end and a mode button. 
The VID and PID of the device in USBDeview are 0e8f and 0003 respectively.  
My idea is that the initial "handshake" makes the device return its playstation mode or something like that but then it outputs as if it was a pc, but I am very likely wrong as it was fine in the past. I am attaching 2 log files, one where the controller has a mode where the correct VID and PID are in the config and another one where they aren't

**Logs**
- Attach your logs /config/sys-con/log.log to the ticket "Trace" mode (https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs)
- Attach your /config/sys-con/config.ini
[logs_2.zip](https://github.com/user-attachments/files/18247016/logs_2.zip)
[logs.zip](https://github.com/user-attachments/files/18247002/logs.zip)

Note: You will have to **zip** your config.ini and log.log in order to attach them to your ticket

**Comment by o0Zz** [comment]
Hi, thanks for the report and good catch. I don't have any PS3 controller at home, thus I can't test it. You are right, there is a regression introduced in v1.4.0 - This version should fix the issue. Let me know if its better.
[sys-con-1.4.3+8-ATMOSPHERE-1.7.x-1.8.x.zip](https://github.com/user-attachments/files/18247238/sys-con-1.4.3%2B8-ATMOSPHERE-1.7.x-1.8.x.zip)

**Comment by zionhian** [comment]
Seems to be working.
Thank you very much
