### ISSUE TITLE
Hama Thunder v5 wheel support

### ISSUE THREAD

**Issue by macsimc** [o0Zz/sys-con#57]
I was trying to connect the wheel to the switch using your module.
If i connect it to the pc it shows as "PS(R) Gamepad Adaptor" and works as expected without any driver:
![image](https://github.com/user-attachments/assets/abdc7851-ad3f-40c8-a998-190f96805cea)

On switch it is detected as a different vid/pid pair as a "Dualshock 3" [log.log](https://github.com/user-attachments/files/18251543/log.log) but it does not seem to work in the interface (not seen in controllers, not sending any keys when using the sys-con applet,etc.)
The module works since i could test a Xbox one wired controller.

Any idea what can i try to make it work?
Thanks in advance!

Just a mention,If i start the console with the wheel connected and MissionControl enabled it crashes so i disabled it.

**Comment by zionhian** [comment]
Exact same issue as I had here: https://github.com/o0Zz/sys-con/issues/56 As it even shows up as the same device
There is a new version of sys-con attached in it, that worked for me. Give it a try

**Comment by o0Zz** [comment]
Like described by Zionhian this issue is already fixed in a previous ticket. I will probably release a new version during the weekend
