### ISSUE TITLE
Problems with Logitech G920

### ISSUE THREAD

**Issue by PieroBarcellos** [o0Zz/sys-con#7]
I have a Logitech G920 [046d-c261] steering wheel that partially worked when I included "driver=xboxone" below VID/PID.  It recognizes the buttons, but acts as if the right stick is always pressed up. And steering wheel movements are not recognized.

**Comment by o0Zz** [comment]
As mentionned in the bug template, you have to provide logs, otherwise you will receive not helps

**Comment by o0Zz** [comment]
Did you progress on this issue ? other I will close the ticket. Do you have logs to provide ?
The fact that this wheel is PC compatible means you don't have to use xboxone implementation and you can use the generic implementation (do not set driver= or profile=). Then you will probably have to map your buttons. Follow the troubleshooting guide -> https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md

**Comment by o0Zz** [comment]
I close this ticket since there is no progress on it. If you have update feel free to re-open it.
FYI: A new version is available ->https://github.com/o0Zz/sys-con/releases/ but as your issue looks to be a mapping issue (configuration only) it should not fix the issue you described.
